todapp/urls.py
from django.urls import path
from .views import home, TodoItemCreateView, TodoItemDeleteView, TodoItemUpdateView, updatedone

app_name = 'todoapp'

urlpatterns = [
    path('home/', home.as_view(), name = 'home-url'),
    path('create/', TodoItemCreateView.as_view(), name = 'create'),
    path('update/<pk>/', TodoItemUpdateView.as_view(), name = 'update'),
    path('delete/<pk>', TodoItemDeleteView, name = 'delete'),
    path('update-done/<pk>',updatedone,name="update-done"),

]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todapp.urls', namespace='todoapp')),
]

todapp/models.py
from django.db import models
from django.shortcuts import reverse
from datetime import datetime as dt
import datetime

# Create your models here.


Choices = ("All", "Grocery", "Personal", "Work")

TAG_CHOICES = ["Overdue", "Today", "Tomorrow", "Long Term"]


class TodoItem(models.Model):
    todoitem = models.CharField(default = "Todo task", max_length = 50)
    note = models.CharField(blank = True, null = True, max_length = 50)
    completed = models.BooleanField(default = False)
    due_date = models.DateField(default = datetime.date.today)

    @property
    def get_tag(self):
        due_date = self.due_date
        today = datetime.date.today()
        timedelta = datetime.timedelta(days = 1)
        yesterday = today - timedelta
        tomorrow = today + timedelta
        if due_date == today:
            return TAG_CHOICES[1]
        elif due_date == yesterday:
            return TAG_CHOICES[0]
        elif due_date == tomorrow:
            return TAG_CHOICES[2]
        elif due_date > tomorrow:
            return TAG_CHOICES[3]

    def __str__(self):
        return f"{self.todoitem}"

    def get_absolute_url(self):
        return reverse('todoapp:home-url')

todapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from .models import TodoItem
from .models import TAG_CHOICES
from django.http import HttpResponseRedirect


class home(ListView):
    model = TodoItem

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag_choices"] = TAG_CHOICES
        context["print"] = "DFFDF"
        return context


class TodoItemCreateView(CreateView):
    model = TodoItem
    fields = ['todoitem', 'note', 'completed', 'due_date']


class TodoItemUpdateView(UpdateView):
    model = TodoItem
    fields = ['todoitem', 'note', 'completed', 'due_date']


def TodoItemDeleteView(request, pk):
    todo = TodoItem.objects.get(pk = pk)
    todo.delete()
    return redirect("todoapp:home-url")


def updatedone(request, pk):
    item = TodoItem.objects.get(pk = pk)
    if item.completed:
        item.completed = False
    else:
        item.completed = True
    item.save()
    return redirect("todoapp:home-url")

todapp/templates/todapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/todoapp/base.css">
    <title>App- Test</title>
</head>
<body >
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
          <a class="navbar-brand font-weight-bold" href="#" > Tod App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item ">
                <a class="nav-link active" href="{% url 'todoapp:home-url' %}">Home </a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'todoapp:create' %}">New</a>
              </li>
            </ul>
          </div>
        </nav>

    </header>
    <div class="container-fluid-sm">
        <div class="d-flex flex-wrap-reverse justify-content-center">
            <div class="col-sm-9">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </div>




</html>

todapp/templates/todapp/todoitem_form.html
{% extends 'todapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="content-section">
        <form method="POST">{%csrf_token%}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Todo</legend>
                    {{form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
        </div>
    </div>

{% endblock %}


todapp/templates/todapp/todoitem_list.html
{% extends 'todapp/base.html' %}}

{% block content %}
    <div class="container">
        {% for tag in tag_choices %}
        <legend id="collapse-main" class="btn btn-primary border-bottom collapsed" style="border: 2pt; background-color: "  data-toggle="collapse" data-target="#{{tag}}1" ></legend>
            <div class="collapse show" id="{{tag}}1">
            <legend id="collapse-toggle" class="btn btn-outline-light btn-lg btn-block border-bottom mb-2 text-primary  font-weight-bold text-left collapsed" data-toggle="collapse" data-target="#{{tag}}">{{tag}}</legend>
            <div class="collapse show" id="{{tag}}">
            <ul class="list-group" >
                {% for todo in object_list %}
                {% if todo.get_tag == tag %}
                <li  aria-disabled="true" style="list-style: none;">
                    <div class="form-control mb-1 d-flex flex-row justify-content-between flex-wrap" aria-label="Note associated with checkbox">
                            <div class="d-flex flex-row justify-content-start flex-wrap align-items-center">
                                <form  action="{% url 'todoapp:update-done' todo.pk %}" method="POST">{% csrf_token%}
                                    <input  class="btn btn-primary mr-2" type="submit" value="">
                                 </form>
                                {% if todo.completed %}
                                 <a style="text-decoration: line-through; margin-right: 10px;" href="{% url 'todoapp:update' todo.pk %}">{{todo.todoitem}} </a>
                                 {% else %}
                                    <a style="text-decoration:none;  margin-right: 10px;" href="{% url 'todoapp:update' todo.pk %}">{{todo.todoitem}}</a>
                                 {% endif %}
                                 {% if todo.note %}
                                    <button type="button" class="btn btn-primary btn-sm  pr-4 pl-4" style="border-radius: 15px;" data-container="body" data-trigger="focus"  data-toggle="popover" data-placement="bottom" data-content="{{todo.note}}" >
                                    Note
                                    </button>
                                  {% endif %}
                            </div>
                            <a href="{% url 'todoapp:delete' todo.pk %}">
                                <svg class="bi bi-trash float-right" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 016 6v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm2.5 0a.5.5 0 01.5.5v6a.5.5 0 01-1 0V6a.5.5 0 01.5-.5zm3 .5a.5.5 0 00-1 0v6a.5.5 0 001 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 01-1 1H13v9a2 2 0 01-2 2H5a2 2 0 01-2-2V4h-.5a1 1 0 01-1-1V2a1 1 0 011-1H6a1 1 0 011-1h2a1 1 0 011 1h3.5a1 1 0 011 1v1zM4.118 4L4 4.059V13a1 1 0 001 1h6a1 1 0 001-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" clip-rule="evenodd"/>
                                </svg>
                            </a>
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
            </div>
        </div>
        {% endfor %}
    </div>

<script>

$(function () {
$('[data-toggle="popover"]').popover()
})

$('.popover-dismiss').popover({
trigger: 'focus'
})
</script>

{% endblock %}
